apiVersion: v1
kind: Service
metadata:
  labels:
    app: sc-deployment
  name: sc-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: sc-deployment
  type: LoadBalancer
